{% set name = "hypso" %}
{% set version = "1.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NTNU-SmallSat-Lab/hypso-package/archive/v{{ version }}.tar.gz
  sha256: 58531d255ffdb81e76a56913d7a1693c189161b6d51eebc31583caa3ad1115c2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61.0
    - setuptools_scm  >=3.4
  run:
    - python >=3.9
    - numpy >=1.24
    - gdal =3.6.2
    - cartopy >=0.21.1
    - pandas
    - matplotlib-base
    - geopandas >=0.12.2
    - rasterio >=1.3.4
    - pyproj >=3.4.1
    - netcdf4 >=1.6.3
    - scikit-image >=0.21.0
    - py6s >=1.9.2
    - scipy >=1.11.2
    - pillow
    - shapely >=2.0.1
    - tqdm >=4.66.1
    - astropy >=5.3.4
    - pyorbital >=1.8.0
    - progressbar >=2.5
    - h5py >=3.8.0
    - pyhdf >=0.11.3
    - pyresample >=1.27.1
    - pygrib >=2.1.4
    - requests
    - python-dateutil
    - scikit-learn >=1.3.2
    - packaging

test:
  imports:
    - hypso
  commands:
    - pip check
    - pip list
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/NTNU-SmallSat-Lab/hypso-package
  summary: 'HYPSO Toolbox For Satellite Image Processing'
  description: |
    hypso is a simple, fast visualization tool for the hyperspectral
    images taken by the HYPSO mission from the Norwegian University of Science and
    Technology (NTNU) for Python 3.9


extra:
  recipe-maintainers:
    - DevAlvaroF

