{% set name = "hypso" %}
{% set version = "1.9.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NTNU-SmallSat-Lab/hypso-package/archive/v{{ version }}.tar.gz
  sha256: 955e2b7e7cafe671c514791b01d41f1dd64cac9f33d79755d0c8ec8711da5fe0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61.0
    - setuptools_scm  >=3.4
  run:
    - python >=3.9
    - numpy >=1.24
    - gdal =3.6.2
    - cartopy >=0.21.1
    - pandas
    - matplotlib-base
    - rasterio >=1.3.4
    - pyproj >=3.4.1
    - netcdf4 >=1.6.3
    - scikit-image >=0.21.0
    - py6s >=1.9.2
    - scipy >=1.11.2
    - pillow
    - shapely >=2.0.1
    - tqdm >=4.66.1
    - astropy >=5.3.4
    - progressbar >=2.5
    - requests
    - python-dateutil
    - scikit-learn >=1.4
    - py-xgboost-cpu

test:
  imports:
    - hypso
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/NTNU-SmallSat-Lab/hypso-package
  summary: 'HYPSO Toolbox For Satellite Image Processing'
  description: |
    hypso is a simple, fast visualization tool for the hyperspectral
    images taken by the HYPSO mission from the Norwegian University of Science and
    Technology (NTNU) for Python 3.9


extra:
  recipe-maintainers:
    - DevAlvaroF
    
